# Generated by Django 5.2.3 on 2025-06-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_aluno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
